In [1]:
import pandas as pd
import numpy as np

In [4]:
Ridership_per_Dock = pd.read_csv('/Users/howardlin/Desktop/DEPA data/dock turnover rate/dock turnover rate.csv', skiprows=0)

In [8]:
Ridership_per_Dock

,station_key,station_name,station_dock_in_service,station_geometry,Ridership_per_Dock
0,2,Dauphin Ave & 103rd St,15,POINT (-87.607662678 41.707250368),0.006122
1,3,Cottage Grove Ave & 111th Pl,15,POINT (-87.610001564 41.691709758),0.010204
2,4,Vernon Ave & 107th St,14,POINT (-87.61225998399999 41.700121379),0.011297
3,5,Halsted St & 96th St,15,POINT (-87.643019557 41.719712184),0.010884
4,6,Greenwood Ave & 97th St,15,POINT (-87.597035766 41.718703155),0.021429
...,...,...,...,...,...
640,651,Michigan Ave & Washington St,43,POINT (-87.624683976 41.883984065),1.526578
641,652,Keystone Ave & Fullerton Ave,11,POINT (-87.72785 41.92459),0.339981
642,653,Lake Shore Dr & Monroe St,39,POINT (-87.616743 41.880958),3.120356
643,654,Millennium Park,47,POINT (-87.62408431999999 41.8810317),2.108120
644,655,Dearborn St & Monroe St,39,POINT (-87.629520919 41.881319815),1.166928

In [7]:
Ridership_per_Dock=Ridership_per_Dock.rename(columns={"dock_turnover_rate": "Ridership_per_Dock"})

In [16]:
Ridership_per_Dock [['no-use','longitude','latitude']] = Ridership_per_Dock.station_geometry.str.split(expand=True)

In [17]:
Ridership_per_Dock

,station_key,station_name,station_dock_in_service,station_geometry,Ridership_per_Dock,no-use,longitude,latitude
0,2,Dauphin Ave & 103rd St,15,POINT (-87.607662678 41.707250368),0.006122,POINT,(-87.607662678,41.707250368)
1,3,Cottage Grove Ave & 111th Pl,15,POINT (-87.610001564 41.691709758),0.010204,POINT,(-87.610001564,41.691709758)
2,4,Vernon Ave & 107th St,14,POINT (-87.61225998399999 41.700121379),0.011297,POINT,(-87.61225998399999,41.700121379)
3,5,Halsted St & 96th St,15,POINT (-87.643019557 41.719712184),0.010884,POINT,(-87.643019557,41.719712184)
4,6,Greenwood Ave & 97th St,15,POINT (-87.597035766 41.718703155),0.021429,POINT,(-87.597035766,41.718703155)
...,...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,43,POINT (-87.624683976 41.883984065),1.526578,POINT,(-87.624683976,41.883984065)
641,652,Keystone Ave & Fullerton Ave,11,POINT (-87.72785 41.92459),0.339981,POINT,(-87.72785,41.92459)
642,653,Lake Shore Dr & Monroe St,39,POINT (-87.616743 41.880958),3.120356,POINT,(-87.616743,41.880958)
643,654,Millennium Park,47,POINT (-87.62408431999999 41.8810317),2.108120,POINT,(-87.62408431999999,41.8810317)
644,655,Dearborn St & Monroe St,39,POINT (-87.629520919 41.881319815),1.166928,POINT,(-87.629520919,41.881319815)

In [25]:
Ridership_per_Dock [['no-use2','longitude']] = Ridership_per_Dock.longitude.str.split("(",expand=True)

In [28]:
Ridership_per_Dock

,station_key,station_name,station_dock_in_service,station_geometry,Ridership_per_Dock,no-use,longitude,latitude,no-use2,no-use3
0,2,Dauphin Ave & 103rd St,15,POINT (-87.607662678 41.707250368),0.006122,POINT,-87.607662678,,,41.707250368
1,3,Cottage Grove Ave & 111th Pl,15,POINT (-87.610001564 41.691709758),0.010204,POINT,-87.610001564,,,41.691709758
2,4,Vernon Ave & 107th St,14,POINT (-87.61225998399999 41.700121379),0.011297,POINT,-87.61225998399999,,,41.700121379
3,5,Halsted St & 96th St,15,POINT (-87.643019557 41.719712184),0.010884,POINT,-87.643019557,,,41.719712184
4,6,Greenwood Ave & 97th St,15,POINT (-87.597035766 41.718703155),0.021429,POINT,-87.597035766,,,41.718703155
...,...,...,...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,43,POINT (-87.624683976 41.883984065),1.526578,POINT,-87.624683976,,,41.883984065
641,652,Keystone Ave & Fullerton Ave,11,POINT (-87.72785 41.92459),0.339981,POINT,-87.72785,,,41.92459
642,653,Lake Shore Dr & Monroe St,39,POINT (-87.616743 41.880958),3.120356,POINT,-87.616743,,,41.880958
643,654,Millennium Park,47,POINT (-87.62408431999999 41.8810317),2.108120,POINT,-87.62408431999999,,,41.8810317
644,655,Dearborn St & Monroe St,39,POINT (-87.629520919 41.881319815),1.166928,POINT,-87.629520919,,,41.881319815

In [27]:
Ridership_per_Dock [['latitude','no-use3']] = Ridership_per_Dock.latitude.str.split(")",expand=True)

In [31]:
Ridership_per_Dock=Ridership_per_Dock.drop(columns=["no-use",'latitude','no-use2'])

In [32]:
Ridership_per_Dock=Ridership_per_Dock.rename(columns={"no-use3": "latitude"})

In [33]:
Ridership_per_Dock

,station_key,station_name,station_dock_in_service,station_geometry,Ridership_per_Dock,longitude,latitude
0,2,Dauphin Ave & 103rd St,15,POINT (-87.607662678 41.707250368),0.006122,-87.607662678,41.707250368
1,3,Cottage Grove Ave & 111th Pl,15,POINT (-87.610001564 41.691709758),0.010204,-87.610001564,41.691709758
2,4,Vernon Ave & 107th St,14,POINT (-87.61225998399999 41.700121379),0.011297,-87.61225998399999,41.700121379
3,5,Halsted St & 96th St,15,POINT (-87.643019557 41.719712184),0.010884,-87.643019557,41.719712184
4,6,Greenwood Ave & 97th St,15,POINT (-87.597035766 41.718703155),0.021429,-87.597035766,41.718703155
...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,43,POINT (-87.624683976 41.883984065),1.526578,-87.624683976,41.883984065
641,652,Keystone Ave & Fullerton Ave,11,POINT (-87.72785 41.92459),0.339981,-87.72785,41.92459
642,653,Lake Shore Dr & Monroe St,39,POINT (-87.616743 41.880958),3.120356,-87.616743,41.880958
643,654,Millennium Park,47,POINT (-87.62408431999999 41.8810317),2.108120,-87.62408431999999,41.8810317
644,655,Dearborn St & Monroe St,39,POINT (-87.629520919 41.881319815),1.166928,-87.629520919,41.881319815

In [34]:
Ridership_per_Dock.to_csv('/Users/howardlin/Desktop/DEPA data/dock turnover rate/Ridership_per_Dock.csv',index=False)