In [1]:
import pandas as pd
import numpy as np

In [2]:
startstation = pd.read_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/tableau_startstation_vs_trip1.csv', skiprows=0)
endstation = pd.read_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/tableau_endstation_vs_trip1.csv', skiprows=0)

In [3]:
startstation['Total']=startstation['Morning']+startstation['Afternoon']+startstation['Evening']+startstation['Night']
endstation['Total']=endstation['Morning']+endstation['Afternoon']+endstation['Evening']+endstation['Night']

In [4]:
startstation

,Start Station Key,Station Name,Station Geometry,Morning,Afternoon,Evening,Night,Total
0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),5.0,7,5,1.0,18.0
1,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),3.0,12,12,3.0,30.0
2,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),2.0,7,18,4.0,31.0
3,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),9.0,14,7,2.0,32.0
4,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),11.0,5,43,4.0,63.0
...,...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),2151.0,4535,4452,1718.0,12856.0
641,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),216.0,305,161,50.0,732.0
642,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),3374.0,9760,9257,1456.0,23847.0
643,654,Millennium Park,POINT (-87.62408431999999 41.8810317),2182.0,7341,7180,2709.0,19412.0
644,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),1108.0,3659,3604,548.0,8919.0

In [5]:
endstation = endstation.fillna(value={'Morning': 0, 'Afternoon': 0, 'Evening': 0,'Night': 0})

In [6]:
startstation = startstation.fillna(value={'Morning': 0, 'Afternoon': 0, 'Evening': 0,'Night': 0})

In [7]:
startstation = startstation.drop(columns=['Morning','Afternoon','Evening','Night'])
endstation = endstation.drop(columns=['Morning','Afternoon','Evening','Night'])

In [8]:
merges=startstation.merge(endstation, left_on='Start Station Key', right_on='End Station Key', how='inner')

In [9]:
merges

,Start Station Key,Station Name,Station Geometry,Total_x,End Station Key,Station Name (Dim Station1),Station Geometry (Dim Station1),Total_y
0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),18.0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),NaN
1,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),30.0,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),30.0
2,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),31.0,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),NaN
3,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),32.0,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),26.0
4,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),63.0,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),61.0
...,...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),12856.0,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),12798.0
641,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),732.0,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),854.0
642,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),23847.0,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),23532.0
643,654,Millennium Park,POINT (-87.62408431999999 41.8810317),19412.0,654,Millennium Park,POINT (-87.62408431999999 41.8810317),20133.0
644,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),8919.0,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),8713.0

In [11]:
merges[merges['Start Station Key']-merges['End Station Key']==0]

,Start Station Key,Station Name,Station Geometry,Total_x,End Station Key,Station Name (Dim Station1),Station Geometry (Dim Station1),Total_y
0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),18.0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),NaN
1,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),30.0,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),30.0
2,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),31.0,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),NaN
3,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),32.0,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),26.0
4,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),63.0,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),61.0
...,...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),12856.0,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),12798.0
641,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),732.0,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),854.0
642,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),23847.0,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),23532.0
643,654,Millennium Park,POINT (-87.62408431999999 41.8810317),19412.0,654,Millennium Park,POINT (-87.62408431999999 41.8810317),20133.0
644,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),8919.0,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),8713.0

In [14]:
merges['diff'] = (merges['Total_x']-merges['Total_y'])

In [15]:
merge1 = merges.drop(columns=['End Station Key','Station Name (Dim Station1)','Station Geometry (Dim Station1)'])

In [16]:
merge1["bike-out more than bike-in"]=(merge1['diff']>0)

In [17]:
merge1.to_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/total.csv',index=False)

In [18]:
ride_perdock = pd.read_csv('/Users/howardlin/Desktop/DEPA data/dock turnover rate/Ridership_per_Dock.csv', skiprows=0)

In [19]:
merge2=merge1.merge(ride_perdock, left_on='Start Station Key', right_on='station_key', how='inner')

In [21]:
merge2=merge2.drop(columns=['station_key','station_name','station_geometry'])

In [22]:
merge2.to_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/totaldiff & perdock.csv',index=False)