In [113]:
import pandas as pd
import numpy as np

In [114]:
startstation = pd.read_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/tableau_startstation_vs_trip1.csv', skiprows=0)
endstation = pd.read_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/tableau_endstation_vs_trip1.csv', skiprows=0)

In [115]:
startstation

,Start Station Key,Station Name,Station Geometry,Morning,Afternoon,Evening,Night
0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),5.0,7,5,1.0
1,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),3.0,12,12,3.0
2,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),2.0,7,18,4.0
3,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),9.0,14,7,2.0
4,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),11.0,5,43,4.0
...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),2151.0,4535,4452,1718.0
641,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),216.0,305,161,50.0
642,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),3374.0,9760,9257,1456.0
643,654,Millennium Park,POINT (-87.62408431999999 41.8810317),2182.0,7341,7180,2709.0
644,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),1108.0,3659,3604,548.0

In [116]:
endstation

,End Station Key,Station Name (Dim Station1),Station Geometry (Dim Station1),Morning,Afternoon,Evening,Night
0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),NaN,8.0,5.0,5.0
1,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),3.0,13.0,11.0,3.0
2,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),2.0,9.0,20.0,NaN
3,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),6.0,8.0,10.0,2.0
4,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),4.0,10.0,40.0,7.0
...,...,...,...,...,...,...,...
642,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),2816.0,4281.0,3689.0,2012.0
643,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),99.0,290.0,325.0,140.0
644,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),3170.0,9671.0,9118.0,1573.0
645,654,Millennium Park,POINT (-87.62408431999999 41.8810317),2896.0,7701.0,6650.0,2886.0
646,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),3911.0,2507.0,1602.0,693.0

In [117]:
endstation = endstation.fillna(value={'Morning': 0, 'Afternoon': 0, 'Evening': 0,'Night': 0})

In [118]:
startstation = startstation.fillna(value={'Morning': 0, 'Afternoon': 0, 'Evening': 0,'Night': 0})

In [119]:
startmorning = startstation.iloc[:,0:4]
startafternoon = startstation.iloc[:,[0,1,2,4]]
startevening = startstation.iloc[:,[0,1,2,5]]
startnight = startstation.iloc[:,[0,1,2,6]]
endmorning = endstation.iloc[:,0:4]
endafternoon = endstation.iloc[:,[0,1,2,4]]
endevening = endstation.iloc[:,[0,1,2,5]]
endnight = endstation.iloc[:,[0,1,2,6]]

In [120]:
morningmerge=startmorning.merge(endmorning, left_on='Start Station Key', right_on='End Station Key', how='inner')
afternoonmerge=startafternoon.merge(endafternoon, left_on='Start Station Key', right_on='End Station Key', how='inner')
eveningmerge=startevening.merge(endevening, left_on='Start Station Key', right_on='End Station Key', how='inner')
nightmerge=startnight.merge(endnight, left_on='Start Station Key', right_on='End Station Key', how='inner')

In [121]:
nightmerge

,Start Station Key,Station Name,Station Geometry,Night_x,End Station Key,Station Name (Dim Station1),Station Geometry (Dim Station1),Night_y
0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),1.0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),5.0
1,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),3.0,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),3.0
2,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),4.0,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),0.0
3,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),2.0,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),2.0
4,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),4.0,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),7.0
...,...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),1718.0,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),2012.0
641,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),50.0,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),140.0
642,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),1456.0,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),1573.0
643,654,Millennium Park,POINT (-87.62408431999999 41.8810317),2709.0,654,Millennium Park,POINT (-87.62408431999999 41.8810317),2886.0
644,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),548.0,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),693.0

In [122]:
nightmerge[nightmerge['Start Station Key']-nightmerge['End Station Key']==0]

,Start Station Key,Station Name,Station Geometry,Night_x,End Station Key,Station Name (Dim Station1),Station Geometry (Dim Station1),Night_y
0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),1.0,2,Dauphin Ave & 103rd St,POINT (-87.607662678 41.707250368),5.0
1,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),3.0,3,Cottage Grove Ave & 111th Pl,POINT (-87.610001564 41.691709758),3.0
2,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),4.0,4,Vernon Ave & 107th St,POINT (-87.61225998399999 41.700121379),0.0
3,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),2.0,5,Halsted St & 96th St,POINT (-87.643019557 41.719712184),2.0
4,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),4.0,6,Greenwood Ave & 97th St,POINT (-87.597035766 41.718703155),7.0
...,...,...,...,...,...,...,...,...
640,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),1718.0,651,Michigan Ave & Washington St,POINT (-87.624683976 41.883984065),2012.0
641,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),50.0,652,Keystone Ave & Fullerton Ave,POINT (-87.72785 41.92459),140.0
642,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),1456.0,653,Lake Shore Dr & Monroe St,POINT (-87.616743 41.880958),1573.0
643,654,Millennium Park,POINT (-87.62408431999999 41.8810317),2709.0,654,Millennium Park,POINT (-87.62408431999999 41.8810317),2886.0
644,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),548.0,655,Dearborn St & Monroe St,POINT (-87.629520919 41.881319815),693.0

In [123]:
morningmerge['diff'] = (morningmerge['Morning_x']-morningmerge['Morning_y'])
afternoonmerge['diff'] = (afternoonmerge['Afternoon_x']-afternoonmerge['Afternoon_y'])
eveningmerge['diff'] = (eveningmerge['Evening_x']-eveningmerge['Evening_y'])
nightmerge['diff'] = (nightmerge['Night_x']-nightmerge['Night_y'])

In [124]:
morning1 = morningmerge.drop(columns=['End Station Key','Morning_x','Station Name (Dim Station1)','Station Geometry (Dim Station1)','Morning_y'])
afternoon1 = afternoonmerge.drop(columns=['End Station Key','Afternoon_x','Station Name (Dim Station1)','Station Geometry (Dim Station1)','Afternoon_y'])
evening1 = eveningmerge.drop(columns=['End Station Key','Evening_x','Station Name (Dim Station1)','Station Geometry (Dim Station1)','Evening_y'])
night1 = nightmerge.drop(columns=['End Station Key','Night_x','Station Name (Dim Station1)','Station Geometry (Dim Station1)','Night_y'])

In [125]:
morning1["bike-out more than bike-in"]=(morning1['diff']>0)
afternoon1["bike-out more than bike-in"]=(afternoon1['diff']>0)
evening1["bike-out more than bike-in"]=(evening1['diff']>0)
night1["bike-out more than bike-in"]=(night1['diff']>0)

In [126]:
morning1.to_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/morning.csv',index=False)
afternoon1.to_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/afternoon.csv',index=False)
evening1.to_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/evening.csv',index=False)
night1.to_csv('/Users/howardlin/Desktop/DEPA data/Bike-out vs bike-in/night.csv',index=False)